# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5s0-fpv5XFfTgNmEM5nuV_CtcEfDJm3
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import os
from financial_health import clean_calculate_store, ask_agent

st.set_page_config(page_title="Autonomous Financial Dashboard", layout="wide")
st.title("📊 Autonomous Financial Health Dashboard")

# Upload data
uploaded_file = st.file_uploader("Upload your Financials CSV", type=["csv"])

if uploaded_file:
    # Save to disk
    file_path = os.path.join("data", "uploaded_financials.csv")
    os.makedirs("data", exist_ok=True)
    with open(file_path, "wb") as f:
        f.write(uploaded_file.read())

    # Clean, calculate, store in Pinecone
    st.write("🔄 Processing and embedding data...")
    metrics, df_cleaned = clean_calculate_store(filepath="Financials.csv")

    # Show metrics
    st.success("✅ Data processed successfully!")
    st.subheader("📈 Key Metrics")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Revenue", f"${metrics['total_revenue']:,.2f}")
    col2.metric("Total Expense", f"${metrics['total_expense']:,.2f}")
    col3.metric("Burn Rate", f"${metrics['burn_rate']:,.2f}")
    col4.metric("Runway", f"{metrics['runway']:.1f} periods")

    # Show chart
    st.subheader("📉 Revenue vs. Expenses Over Time")
    df_cleaned = df_cleaned.sort_values("Date").set_index("Date")
    st.line_chart(df_cleaned[["Sales", "COGS"]])

    # AI Assistant
    st.subheader("🤖 Ask the AI Assistant")
    user_q = st.text_input("Ask a financial question (e.g., 'Why did expenses spike in March 2014?')")

    if user_q:
        with st.spinner("Thinking..."):
            response = ask_agent(user_q)
        st.markdown("### 💬 Answer")
        st.info(response)

else:
    st.info("Upload your financial CSV file to begin.")



